import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/UiComponents/Footer/Footer";
import Navigation from "@/components/UiComponents/Navigation/Navigation";
import CartFlyout from "@/components/UiComponents/CartFlyout/CartFlyout";
import StoreProvider from "@/app/StoreProvider"


// Components Imports

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navigation />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
